### ISSUE TITLE
Index out of range exception when randomizing

### ISSUE THREAD

**Issue by pyroll** [gameboy9/FF6KefkaRush#1]
Often when randomizing a new seed I get this error:

[ff6KRerror.txt](https://github.com/gameboy9/FF6KefkaRush/files/9543292/ff6KRerror.txt)

**Comment by gameboy9** [comment]
Ah, yes, I ran into that as well.  I will fix that in the next version.

**Comment by gameboy9** [comment]
This should be resolved in version 0.2.

**Comment by gameboy9** [comment]
This bug has regressed in version 0.5.  I'll get that fixed in version 0.6...
