### ISSUE TITLE
Reward from beating a scenario does not match what you unlock

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#11]
Sometimes when I complete a scenario I will get espers (i.e. Ragnarok) but it will not be the esper I unlocked when I check afterward.

**Comment by gameboy9** [comment]
Re:  Ragnarok... I have to ask... you didn't get the sword, did you?

**Comment by Stein121** [comment]
I have not

**Comment by Stein121** [comment]
it might not be specifically tied to ragnarok's reward, I was just stating this one as an example cause this is the one I noticed didn't show up in my esper list after finishing the scenario. I'll need to pay more attention the rewards going forward to give more details.

**Comment by gameboy9** [comment]
Going to close this one for now since we can't repro.  We can open this if this is still an issue.
