### ISSUE TITLE
Title soft lock (black screen) at the end of fanatic tower's scenario

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#13]
At the end of the scenario under Diamond difficulty only (the other difficulties are fine) the title will go into black screen forcing user to restart the game.

**Comment by Stein121** [comment]
Seed: 1327830260
Flag: 02a00000

**Comment by Stein121** [comment]
Issue occured again under adamant difficulty in Beta 3

**Comment by Stein121** [comment]
also occurs in version 0.4

**Comment by gameboy9** [comment]
Yeah, there's a really good reason for that; I still haven't beaten that scenario!  😆 

I may have to cheat... 😏

**Comment by gameboy9** [comment]
So I won on Gold difficulty... but I wonder what would happen if I rerun the scenario at a higher difficulty...

**Comment by gameboy9** [comment]
Aha!  Retrying on Diamond gave me an instant victory... and a black screen.  I will investigate further...

Do we have an AI issue or do we have a scenario issue or do we have both?

**Comment by gameboy9** [comment]
I'm 99% sure it's because I was trying to bring in Dungeon's Den Dragons... and their AI doesn't actually exist yet.  They will be removed from play in the next version.
