### ISSUE TITLE
Softlock with wrexsoul in party

### ISSUE THREAD

**Issue by TheBuffalax** [gameboy9/FF6KefkaRush#16]
Did the RAF event, Wrexsoul was my Ultros fight. Only had 1 party member alive. Wrexsoul disappeared and it softlocked the game.

**Comment by TheBuffalax** [comment]
I was able to get out of it by casting Quake on myself to lose the fight.

**Comment by gameboy9** [comment]
While I think you were on version 0.1, I'm 99.9% sure this is still a problem in version 0.3.  I'll take a look at this.

**Comment by gameboy9** [comment]
Ah, I took a look at your VOD; looks like Wrexsoul possessed Relm, so he doesn't come back until the character he possessed either gets KOed, Petrified, or Zombied.

Still, I want to make sure that Wrexsoul is acting appropriately, so I'm going to keep this open for now.

**Comment by TheBuffalax** [comment]
Yeah sorry I'm not used to people updating things so quickly. I'll update to 0.3 when I can.

**Comment by TheBuffalax** [comment]
this shouldnt be an issue with more likelihood of phoenix downs in the game. i just had one character and no way to revive anyone else.

**Comment by gameboy9** [comment]
Yeah, looks like Wrexsoul is operating correctly, so I'm going to close this issue.  If it turns out that there is a problem, we can reopen.
