### ISSUE TITLE
Party member stamped on screen after triggering Siegfried event in ghost train 

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#20]
Some party members might get stamped on screen if you trigger siegfried event in ghost train (after opening chest and fighting him).

https://media.discordapp.net/attachments/1018903473036738640/1020356146671915079/unknown.png?width=1193&height=671
https://media.discordapp.net/attachments/1018903473036738640/1020356515263152239/unknown.png?width=1194&height=670

**Comment by gameboy9** [comment]
Need to either fix the scene or just change the treasure to empty...

**Comment by gameboy9** [comment]
I just wound up engaging the boss fight and opening the empty box with no talking or acting.
