### ISSUE TITLE
Random enemy encounters are the same across all difficulty in ghost train scenario

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#21]
Random enemy encounters are the same across all difficulty in ghost train scenario. They seem to be all set at bronze level.

**Comment by gameboy9** [comment]
This is related to issue #10.

I am not sure if I can do anything about that... while I could theoretically make new map entries pointing to the same map with different monster sets, as soon as you change maps (that will happen in the Phantom Train), the encounters will reset to default.

Therefore, I'm probably going to have to default to what I was planning to do in issue #10.
