### ISSUE TITLE
Title Freeze/hang in opera and air force scenario.

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#22]
The title will Freeze/hang when fighting Ultros at gold and adamant difficulty in Opera Scenario.

Seed: 1355788935
Flag: 0440000

**Comment by Stein121** [comment]
Same crash Freeze/hang occured also in air force scenario under diamond and adamant difficulty.

**Comment by Stein121** [comment]
Seems to freeze/hang when there's multiple Ultros on the screen

**Comment by gameboy9** [comment]
Initially there was indeed a bug that froze the battle... but when I fixed that, if you fought Ultros3 by itself, the game automatically gave you the victory.  Therefore, I am simplifying his AI.  This will be available in the next version.
