### ISSUE TITLE
Wiping in lethe river and selecting that scenario again will bring you back to the scenario selection screen

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#26]
whenever you wipe in lethe river and select that scenario again you will be returned to the scenario selection screen (once)

**Comment by gameboy9** [comment]
Ahhhh... need to remove the "wiped out; you lose" business.  I also may need to reset some more flags.  Researching...

**Comment by gameboy9** [comment]
This will be resolved in the next version.
