### ISSUE TITLE
Some espers appears as mastered

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#28]
Some espers appears as mastered even though spells from it are not learned yet.
https://media.discordapp.net/attachments/1018903473036738640/1020526937392824410/unknown.png?width=1193&height=671

**Comment by gameboy9** [comment]
I think that it's because I've double awarded magicite.  Also, issue #27 may be assisting in this issue.  (This will be coupled with issue #24)

**Comment by gameboy9** [comment]
I believe this is corrected and will be in the next release.
