### ISSUE TITLE
falcon invasion scenario does not end when timer reaches 0:00

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#30]
The scenario only ended once I reached the threshold for adamant rewards, even though the timer was 0:00, I was still able to walk around and fight enemies.

**Comment by gameboy9** [comment]
I think that I'm going to need to see a video in order to help correct this issue.

**Comment by Stein121** [comment]
My recording tool doesn't seem to want to cooperate but I reproduced the issue, if you enter battle when there's 30~ seconds left then finish the battle when timer is at 0, it will stay at 0 and you can take as long as you want after that to attempt to get adamant rewards. 

Steps
- 1.enter falcon scenario
- 2.wait until 30 seconds or so
- 3.enter battle and wait until timer reaches 0
- 4.finish battle

**Comment by gameboy9** [comment]
Ah, looks like I have to run a battle script on anything that's timed.  Interesting.  Alright, I'll have a look.

**Comment by TheBuffalax** [comment]
it seems like, for the once ive done it at least, that the timer ended at actual 5 minutes and not when the timer hit 0:00

**Comment by gameboy9** [comment]
This will be resolved in the next release.
