### ISSUE TITLE
Intangir

### ISSUE THREAD

**Issue by TheBuffalax** [gameboy9/FF6KefkaRush#35]
intangir was in a boss fight, and fled, and the game is softlocked on the victory screen.

**Comment by gameboy9** [comment]
I saw the video... and I was thinking that maybe the King Behemoth would mess things up because it should transition to Undead King Behemoth... but that didn't happen.  A puzzling one... may have to exclude Intangirs for the time being.

**Comment by gameboy9** [comment]
I can't seem to duplicate.  May I have seed and flags, please?

**Comment by TheBuffalax** [comment]
045@Fy0 1836350270

**Comment by TheBuffalax** [comment]
that's correct if the program stays on the last seed you generated when you open it up again

**Comment by gameboy9** [comment]
I still can't seem to repro the issue... so I think that I'm going to need to exclude Intangir for the time being.  (that kind of stinks...)
