### ISSUE TITLE
Lethe River scenario ends abrubtly when Ultros fight begins

### ISSUE THREAD

**Issue by pyroll** [gameboy9/FF6KefkaRush#4]
When reaching Ultros in Lethe River, the victory menus show up immediately and the battle is won. Awards were still given afterwards, and I was returned to the scenario select screen.

**Comment by gameboy9** [comment]
Interesting... may I have seed and flags, please?  Might be something with the enemy interaction.  Maybe somebody joined Ultros?

**Comment by pyroll** [comment]
So I think it was this seed and I went to try and replicate it, but I encountered two other odd bugs.

v0.1
Flags: 02a00000
Seed: 1969918068

This was after I had beaten it once, attempting again on Bronze. On my first attempt, I think Ultros spawned earlier than he was supposed to, as he showed up in a regular encounter. It looked like he may have had his battle script from when you fight him in the opera or maybe when you get Relm. The scenario ended after I beat him regardless.

Did another Bronze attempt. The second bug I encountered was I got stuck in what seemed to be an endless loop. So if the raft traveled from Point A to Point B, with a battle at Point B, upon winning the battle I'd get teleported back to Point A and the same sequence would repeat itself. Same monster formation and all.

Maybe another Ultros fight got randomized in the scenario and it caused issues?

**Comment by gameboy9** [comment]
Alright, I confirm that there's a problem; you got the Ultros 3 fight  (aka the Relm sketch fight)... and it also happened at an unexpected location.

I think that I need to rewrite this scenario; things were set up differently when I initially wrote it.

Another thing I'll do while I'm at it is to bring back the caves that allow you to get a break.  Otherwise, it's basically just another "Fabul Gauntlet".

**Comment by gameboy9** [comment]
Also, looking more closely at the script, it turns out that I was redirecting the script to the wrong spot when selecting the correct boss fight, so that's incorrect as well...

**Comment by gameboy9** [comment]
With regards to your endless loop, I'm thinking that I should have reset some flags that were set during the first journey down the river.  I will address all of these bugs in the next version.
