### ISSUE TITLE
Enemy npc previously fought on Falcon and defeated by vanishes on next attempt.

### ISSUE THREAD

**Issue by pyroll** [gameboy9/FF6KefkaRush#5]
I had attempted the Falcon scenario and lost to the nearest npc battle. The next time I attempted the scenario and talked to the same npc, he vanished and no battle was started.

**Comment by gameboy9** [comment]
Oh... I know why.  I have a flag that was set and I didn't unset it.  I'll get that taken care of.

**Comment by gameboy9** [comment]
This should be resolved in version 0.2.
