### ISSUE TITLE
Suggestion: Remove game over when Banon dies

### ISSUE THREAD

**Issue by pyroll** [gameboy9/FF6KefkaRush#6]
This would probably go in hand with what we mentioned on Discord about changing how Banon and Leo get added to the randomizer. Whatever event triggers a Game Over when Banon gets KO'd should be removed so can be downed normally like other party members.

**Comment by gameboy9** [comment]
Oh... it's still game over when Banon dies, regardless of location?  Yikes... this might be a tough one to overcome... the temporary solution may be to remove Banon, even though I don't want to...

**Comment by pyroll** [comment]
Someone mentioned you can make as many characters as you want. Maybe it'd be easier to basically make a copy of Banon from scratch and use that. I'm going to start learning how modding the PRs works myself so maybe I can pitch in on how that works at some point.

**Comment by gameboy9** [comment]
Looks like when I redid the character randomization, this bug goes away!  Clearly they check for the character ID being KOed, not the character class.

Therefore, this bug will be fixed in the next version.
