### ISSUE TITLE
Biggs, Wedge, Leo and Banon are useless in fanatic tower

### ISSUE THREAD

**Issue by Stein121** [gameboy9/FF6KefkaRush#9]
unsure about Leo and Banon but I would assume they are useless due to only be able to use magic.

https://media.discordapp.net/attachments/1018903473036738640/1018956038688493679/unknown.png?width=1193&height=671

**Comment by gameboy9** [comment]
I think that now that I have figured out a better way to randomize characters, this won't be an issue starting in the next version.
